# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2be9bf4209c861fced9c18fdb37c6861"
name = "Import Stock Boutique DEV"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_metaobject_definitions,read_metaobjects,read_products,write_inventory,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
